# Autogenerated wrapper script for LibPQ_jll for i686-w64-mingw32
export LIBPQ_HANDLE

using OpenSSL_jll
using ICU_jll
using Zstd_jll
JLLWrappers.@generate_wrapper_header("LibPQ")
JLLWrappers.@declare_library_product(LIBPQ_HANDLE, "libpq.dll")
function __init__()
    JLLWrappers.@generate_init_header(OpenSSL_jll, ICU_jll, Zstd_jll)
    JLLWrappers.@init_library_product(
        LIBPQ_HANDLE,
        "bin\\libpq.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
